import { useEffect, useState } from 'react'
import { createAdminUser, getAdminUsers, updateUserRoles } from '../api/adminUsers'

const roles = ['User', 'Scorer', 'Admin']
export default function AdminUsers({ session }) {
  const [items, setItems] = useState([]); const [status, setStatus] = useState('loading'); const [message, setMessage] = useState(''); const [form, setForm] = useState(null)
  const load = () => { setStatus('loading'); getAdminUsers(session.accessToken).then(data => { setItems(data); setStatus('ready') }).catch(error => { setMessage(error.message); setStatus('error') }) }
  useEffect(() => { load() }, [])
  const toggle = async (user, role) => { const next = user.roles.includes(role) ? user.roles.filter(item => item !== role) : [...user.roles, role]; if (!next.length) { setMessage('Every account must have at least one role.'); return } try { const updated = await updateUserRoles(user.id, next, session.accessToken); setItems(items.map(item => item.id === updated.id ? updated : item)); setMessage(`Roles updated for ${updated.displayName}.`) } catch (error) { setMessage(error.message) } }
  const save = async event => { event.preventDefault(); if (!form.roles.length) { setMessage('Choose at least one role.'); return } try { const created = await createAdminUser(form, session.accessToken); setItems([...items, created]); setForm(null); setMessage(`Staff account created for ${created.displayName}.`) } catch (error) { setMessage(error.message) } }
  const toggleNewRole = role => setForm(current => ({ ...current, roles: current.roles.includes(role) ? current.roles.filter(item => item !== role) : [...current.roles, role] }))
  return <div className="admin-block"><div className="manage-head"><h2>Manage Users</h2><div><button onClick={() => { setMessage(''); setForm({ displayName: '', email: '', password: '', roles: ['Scorer'] }) }}>+ Add staff account</button><button onClick={load}>Refresh</button></div></div><p className="admin-help">Public visitors cannot register. Create Admin or Scorer accounts here, then choose roles for each account. You cannot remove your own Admin role.</p>{message && <p className="admin-message">{message}</p>}{form && <form className="admin-form" onSubmit={save}><h3>Create staff account</h3><label>Display name<input value={form.displayName} onChange={event => setForm({ ...form, displayName: event.target.value })} required /></label><label>Email<input type="email" value={form.email} onChange={event => setForm({ ...form, email: event.target.value })} required /></label><label>Password<input type="password" minLength="8" value={form.password} onChange={event => setForm({ ...form, password: event.target.value })} required /></label><fieldset className="team-selector"><legend>Roles</legend>{roles.filter(role => role !== 'User').map(role => <label key={role}><input type="checkbox" checked={form.roles.includes(role)} onChange={() => toggleNewRole(role)} /> {role}</label>)}</fieldset><div><button className="cta">Create account</button><button type="button" onClick={() => setForm(null)}>Cancel</button></div></form>}{status === 'loading' && <div className="admin-empty">Loading users…</div>}{status === 'error' && <div className="admin-empty">Users could not be loaded.</div>}{status === 'ready' && !items.length && <div className="admin-empty">No staff accounts yet.</div>}{items.length > 0 && <div className="admin-list user-list">{items.map(user => <article key={user.id}><div><b>{user.displayName}</b><span>{user.email}</span></div><div className="role-pills">{roles.map(role => <label key={role}><input type="checkbox" checked={user.roles.includes(role)} onChange={() => toggle(user, role)} /> {role}</label>)}</div></article>)}</div>}</div>
}
