import { useEffect, useState } from 'react'
import { createNews, deleteNews, getAdminNews, updateNews } from '../api/adminNews'

const localDateTime = value => value ? new Date(value).toISOString().slice(0, 16) : ''
const emptyArticle = { title: '', summary: '', content: '', imageUrl: '', isFeatured: false, publishedAt: localDateTime(new Date()) }
export default function AdminNews({ session }) {
  const [items, setItems] = useState([]); const [form, setForm] = useState(null); const [status, setStatus] = useState('loading'); const [message, setMessage] = useState('')
  const load = () => { setStatus('loading'); getAdminNews().then(data => { setItems(data || []); setStatus('ready') }).catch(error => { setMessage(error.message); setStatus('error') }) }
  useEffect(() => { load() }, [])
  const save = async event => { event.preventDefault(); setStatus('saving'); setMessage(''); const payload = { ...form, imageUrl: form.imageUrl.trim() || null, publishedAt: new Date(form.publishedAt).toISOString() }; try { form.id ? await updateNews(form.id, payload, session.accessToken) : await createNews(payload, session.accessToken); setMessage(form.id ? 'Story updated.' : 'Story published.'); setForm(null); load() } catch (error) { setMessage(error.message); setStatus('ready') } }
  const remove = async article => { if (!window.confirm(`Delete “${article.title}”? This cannot be undone.`)) return; try { await deleteNews(article.id, session.accessToken); setMessage('Story deleted.'); load() } catch (error) { setMessage(error.message) } }
  return <div className="admin-block"><div className="manage-head"><h2>Manage News</h2><button className="cta" onClick={() => { setMessage(''); setForm({ ...emptyArticle, publishedAt: localDateTime(new Date()) }) }}>+ Add Story</button></div>{message && <p className="admin-message">{message}</p>}{form && <form className="admin-form" onSubmit={save}><h3>{form.id ? 'Edit story' : 'Publish story'}</h3><label className="wide-field">Title<input value={form.title} onChange={event => setForm({ ...form, title: event.target.value })} required /></label><label className="wide-field">Summary<input value={form.summary} onChange={event => setForm({ ...form, summary: event.target.value })} required /></label><label className="wide-field">Full story<textarea value={form.content} onChange={event => setForm({ ...form, content: event.target.value })} required rows="8" /></label><label>Publication date and time<input type="datetime-local" value={form.publishedAt} onChange={event => setForm({ ...form, publishedAt: event.target.value })} required /></label><label>Image address<input type="url" value={form.imageUrl || ''} onChange={event => setForm({ ...form, imageUrl: event.target.value })} /></label><label className="check-label"><input type="checkbox" checked={form.isFeatured} onChange={event => setForm({ ...form, isFeatured: event.target.checked })} /> Mark as featured</label><div><button className="cta" disabled={status === 'saving'}>{status === 'saving' ? 'Saving…' : 'Save story'}</button><button type="button" onClick={() => setForm(null)}>Cancel</button></div></form>}{status === 'loading' && <div className="admin-empty">Loading stories…</div>}{status === 'error' && <div className="admin-empty">Stories could not be loaded.</div>}{status === 'ready' && !items.length && <div className="admin-empty">No stories yet. Publish the first one above.</div>}{items.length > 0 && <div className="admin-list">{items.map(article => <article key={article.id}><div><b>{article.title}</b><span>{article.isFeatured ? 'Featured · ' : ''}{new Date(article.publishedAt).toLocaleString()}</span></div><div><button onClick={() => { setMessage(''); setForm({ ...article, imageUrl: article.imageUrl || '', publishedAt: localDateTime(article.publishedAt) }) }}>Edit</button><button className="delete-button" onClick={() => remove(article)}>Delete</button></div></article>)}</div>}</div>
}
