import { useEffect, useState } from 'react'
import { createVenue, deleteVenue, getAdminVenues, updateVenue } from '../api/adminVenues'
import { uploadImage } from '../api/uploads'

const emptyVenue = { name: '', city: '', country: '', capacity: '', imageUrl: '' }
export default function AdminVenues({ session }) {
  const [items, setItems] = useState([]); const [search, setSearch] = useState(''); const [form, setForm] = useState(null); const [status, setStatus] = useState('loading'); const [message, setMessage] = useState('')
  const load = () => { setStatus('loading'); getAdminVenues(search).then(data => { setItems(data.items || []); setStatus('ready') }).catch(error => { setMessage(error.message); setStatus('error') }) }
  useEffect(() => { const delay = setTimeout(load, search ? 250 : 0); return () => clearTimeout(delay) }, [search])
  const save = async event => { event.preventDefault(); setStatus('saving'); setMessage(''); const payload = { ...form, capacity: form.capacity === '' ? null : Number(form.capacity), imageUrl: form.imageUrl.trim() || null }; try { form.id ? await updateVenue(form.id, payload, session.accessToken) : await createVenue(payload, session.accessToken); setMessage(form.id ? 'Venue updated.' : 'Venue added.'); setForm(null); load() } catch (error) { setMessage(error.message); setStatus('ready') } }
  const upload = async file => { if (!file) return; try { setMessage('Uploading image…'); const imageUrl = await uploadImage(file, session.accessToken, 'venues'); setForm(current => ({ ...current, imageUrl })); setMessage('Image uploaded. Save the venue to keep it.') } catch (error) { setMessage(error.message) } }
  const remove = async venue => { if (!window.confirm(`Delete ${venue.name}? This cannot be undone.`)) return; try { await deleteVenue(venue.id, session.accessToken); setMessage('Venue deleted.'); load() } catch (error) { setMessage(error.message) } }
  return <div className="admin-block"><div className="manage-head"><h2>Manage Venues</h2><button className="cta" onClick={() => { setMessage(''); setForm({ ...emptyVenue }) }}>+ Add Venue</button></div>{message && <p className="admin-message">{message}</p>}{form && <form className="admin-form" onSubmit={save}><h3>{form.id ? 'Edit venue' : 'Add venue'}</h3><label>Venue name<input value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} required /></label><label>City<input value={form.city} onChange={event => setForm({ ...form, city: event.target.value })} required /></label><label>Country<input value={form.country} onChange={event => setForm({ ...form, country: event.target.value })} required /></label><label>Capacity<input type="number" min="0" value={form.capacity ?? ''} onChange={event => setForm({ ...form, capacity: event.target.value })} /></label><label>Upload venue image<input type="file" accept="image/png,image/jpeg,image/webp" onChange={event => upload(event.target.files?.[0])} /></label><label>Venue image address (optional)<input type="url" value={form.imageUrl || ''} onChange={event => setForm({ ...form, imageUrl: event.target.value })} /></label>{form.imageUrl && <img className="image-preview" src={form.imageUrl} alt="Venue image preview"/>}<div><button className="cta" disabled={status === 'saving'}>{status === 'saving' ? 'Saving…' : 'Save venue'}</button><button type="button" onClick={() => setForm(null)}>Cancel</button></div></form>}<input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search venues…" />{status === 'loading' && <div className="admin-empty">Loading venues…</div>}{status === 'error' && <div className="admin-empty">Venues could not be loaded.</div>}{status === 'ready' && !items.length && <div className="admin-empty">No venues yet. Add the first one above.</div>}{items.length > 0 && <div className="admin-list">{items.map(venue => <article key={venue.id}><div><b>{venue.name}</b><span>{venue.city}, {venue.country}{venue.capacity ? ` · ${venue.capacity.toLocaleString()} capacity` : ''}</span></div><div><button onClick={() => { setMessage(''); setForm({ ...venue, capacity: venue.capacity ?? '', imageUrl: venue.imageUrl || '' }) }}>Edit</button><button className="delete-button" onClick={() => remove(venue)}>Delete</button></div></article>)}</div>}</div>
}
