import { useEffect, useState } from 'react'
import { getAdminTeams } from '../api/adminTeams'
import { createTournament, deleteTournament, getAdminTournaments, updateTournament } from '../api/adminTournaments'

const formats = ['Test', 'ODI', 'T20', 'T10']
const emptyTournament = { name: '', season: '', format: 2, startDate: '', endDate: '', logoUrl: '', teamIds: [] }
export default function AdminTournaments({ session }) {
  const [items, setItems] = useState([]); const [teams, setTeams] = useState([]); const [form, setForm] = useState(null); const [status, setStatus] = useState('loading'); const [message, setMessage] = useState('')
  const load = () => { setStatus('loading'); Promise.all([getAdminTournaments(), getAdminTeams()]).then(([data, teamData]) => { setItems(data.items || []); setTeams(teamData.items || []); setStatus('ready') }).catch(error => { setMessage(error.message); setStatus('error') }) }
  useEffect(() => { load() }, [])
  const toggleTeam = id => setForm(current => ({ ...current, teamIds: current.teamIds.includes(id) ? current.teamIds.filter(teamId => teamId !== id) : [...current.teamIds, id] }))
  const save = async event => { event.preventDefault(); if (!form.teamIds.length) { setMessage('Choose at least one participating team.'); return } setStatus('saving'); setMessage(''); const payload = { ...form, format: Number(form.format), logoUrl: form.logoUrl.trim() || null }; try { form.id ? await updateTournament(form.id, payload, session.accessToken) : await createTournament(payload, session.accessToken); setMessage(form.id ? 'Tournament updated.' : 'Tournament added.'); setForm(null); load() } catch (error) { setMessage(error.message); setStatus('ready') } }
  const remove = async tournament => { if (!window.confirm(`Delete ${tournament.name}? This cannot be undone.`)) return; try { await deleteTournament(tournament.id, session.accessToken); setMessage('Tournament deleted.'); load() } catch (error) { setMessage(error.message) } }
  return <div className="admin-block"><div className="manage-head"><h2>Manage Tournaments</h2><button className="cta" onClick={() => { setMessage(''); setForm({ ...emptyTournament }) }}>+ Add Tournament</button></div>{message && <p className="admin-message">{message}</p>}{form && <form className="admin-form" onSubmit={save}><h3>{form.id ? 'Edit tournament' : 'Add tournament'}</h3><label>Tournament name<input value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} required /></label><label>Season<input value={form.season} placeholder="e.g. 2026" onChange={event => setForm({ ...form, season: event.target.value })} required /></label><label>Format<select value={form.format} onChange={event => setForm({ ...form, format: event.target.value })}>{formats.map((format, index) => <option value={index} key={format}>{format}</option>)}</select></label><label>Logo image address<input type="url" value={form.logoUrl || ''} onChange={event => setForm({ ...form, logoUrl: event.target.value })} /></label><label>Start date<input type="date" value={form.startDate} onChange={event => setForm({ ...form, startDate: event.target.value })} required /></label><label>End date<input type="date" value={form.endDate} min={form.startDate} onChange={event => setForm({ ...form, endDate: event.target.value })} required /></label><fieldset className="team-selector"><legend>Participating teams</legend>{teams.length ? teams.map(team => <label key={team.id}><input type="checkbox" checked={form.teamIds.includes(team.id)} onChange={() => toggleTeam(team.id)} /> {team.name}</label>) : <span>Add teams first, then return here.</span>}</fieldset><div><button className="cta" disabled={status === 'saving'}>{status === 'saving' ? 'Saving…' : 'Save tournament'}</button><button type="button" onClick={() => setForm(null)}>Cancel</button></div></form>}{status === 'loading' && <div className="admin-empty">Loading tournaments…</div>}{status === 'error' && <div className="admin-empty">Tournaments could not be loaded.</div>}{status === 'ready' && !items.length && <div className="admin-empty">No tournaments yet. Add the first one above.</div>}{items.length > 0 && <div className="admin-list">{items.map(tournament => <article key={tournament.id}><div><b>{tournament.name}</b><span>{formats[tournament.format] || tournament.format} · {tournament.season} · {tournament.teams.length} teams</span></div><div><button onClick={() => { setMessage(''); setForm({ ...tournament, format: tournament.format, logoUrl: tournament.logoUrl || '', teamIds: tournament.teams.map(team => team.id) }) }}>Edit</button><button className="delete-button" onClick={() => remove(tournament)}>Delete</button></div></article>)}</div>}</div>
}
